In [ ]:
## pandas section
pandas is open source, easy to use data structure and data analysis tool
point to cover:
1. data frames
2. data series
3. different operations in pandas
4. using pandas we can read and write the data from file
5. read json data format

In [1]:
import pandas as pd
import numpy as np

In [3]:
data1 = np.random.randint(100,size=(2, 4))
data1

array([[24, 33, 57, 99],
       [41, 68, 89, 21]])

In [5]:
df = pd.DataFrame(data1,index=["row1","row2"],columns=["col1","col2","col3","col4"])
df

      col1  col2  col3  col4
row1    24    33    57    99
row2    41    68    89    21

In [7]:
# converting to excel
df.to_csv('out.csv', index=False)  # doctest: +SKIP

In [9]:
# Index accessing element
df.loc['row1']

col1    24
col2    33
col3    57
col4    99
Name: row1, dtype: int32

In [11]:
type(df.loc['row1'])

pandas.core.series.Series

In [13]:
df.iloc[:,0:2]

      col1  col2
row1    24    33
row2    41    68

In [15]:
type(df.iloc[:,0:2])

pandas.core.frame.DataFrame

In [17]:
df

      col1  col2  col3  col4
row1    24    33    57    99
row2    41    68    89    21

In [19]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [21]:
df['col2']

row1    33
row2    68
Name: col2, dtype: int32

In [23]:
type(df)

pandas.core.frame.DataFrame

In [25]:
# read data from csv file

In [137]:
df1 = pd.read_csv("C:\\Users\\Mohan\\python_workspace\\fundamental\\resources\\customer_sample.csv")

In [139]:
df1

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [141]:
df1.to_pickle('df1_csv')

In [31]:
df1.head(3)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/

In [33]:
df1.info(show_counts=3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [35]:
df1.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [37]:
df1['Customer Id'].head(5)

0    DD37Cf93aecA6Dc
1    1Ef7b82A4CAAD10
2    6F94879bDAfE5a6
3    5Cef8BFA16c5e3c
4    053d585Ab6b3159
Name: Customer Id, dtype: object

In [39]:
df1['Customer Id'].value_counts()

Customer Id
DD37Cf93aecA6Dc    1
FCBdfCEAe20A8Dc    1
A3F76Be153Df4a3    1
F560f2d3cDFb618    1
Ef859092FbEcC07    1
                  ..
64DCcDFaB9DFd4e    1
EDA69ca7a6e96a2    1
3B5dAAFA41AFa22    1
b92EBfdF8a3f0E6    1
2354a0E336A91A1    1
Name: count, Length: 100, dtype: int64

In [57]:
from io import StringIO, BytesIO

In [43]:
df2 = ('col1,col2,col3\n'
       'x,y,z\n'
       'a,b,c\n'
       '1,2,3\n')

In [45]:
StringIO()

In [47]:
cs = pd.read_csv(StringIO(df2))

In [49]:
cs

  col1 col2 col3
0    x    y    z
1    a    b    c
2    1    2    3

In [51]:
## using pandas read the json data

In [53]:
jsondata = '''{"menu": {  
  "id": "file",  

  "value": "File",  
  "popup": {  
    "menuitem": [  
      {"value": "New", "onclick": "CreateDoc()"},  
      {"value": "Open", "onclick": "OpenDoc()"},  
      {"value": "Save", "onclick": "SaveDoc()"}  
    ]  
  }  
}}'''

In [133]:

jsonframe = pd.read_json(StringIO(jsondata))
jsonframe

                                                    menu
id                                                  file
value                                               File
popup  {'menuitem': [{'value': 'New', 'onclick': 'Cre...

In [69]:
content = jsonframe.to_string()
content

"                                                                                                                                                   menu\nid                                                                                                                                                 file\nvalue                                                                                                                                              File\npopup  {'menuitem': [{'value': 'New', 'onclick': 'CreateDoc()'}, {'value': 'Open', 'onclick': 'OpenDoc()'}, {'value': 'Save', 'onclick': 'SaveDoc()'}]}"

In [73]:
content = jsonframe.to_json()
content

'{"menu":{"id":"file","value":"File","popup":{"menuitem":[{"value":"New","onclick":"CreateDoc()"},{"value":"Open","onclick":"OpenDoc()"},{"value":"Save","onclick":"SaveDoc()"}]}}}'

In [75]:
type(content)

str

In [79]:
jsonframe.to_json(orient="records")

'[{"menu":"file"},{"menu":"File"},{"menu":{"menuitem":[{"value":"New","onclick":"CreateDoc()"},{"value":"Open","onclick":"OpenDoc()"},{"value":"Save","onclick":"SaveDoc()"}]}}]'

In [103]:
pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\mohan\anaconda3\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in c:\users\mohan\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Note: you may need to restart the kernel to use updated packages.

In [121]:
url = 'https://en.wikipedia.org/wiki/States_and_union_territories_of_India'
pd.read_html(url,match="Tamil Nadu",header=0)

[               States and union territories of India  \
 0  Andhra Pradesh Arunachal Pradesh Assam Bihar C...
 1                                           Category
 2                                           Location
 3                                             Number
 4                                        Populations
 5                                              Areas
 6                                         Government
 7                                       Subdivisions

              States and union territories of India.1
 0  Andhra Pradesh Arunachal Pradesh Assam Bihar C...
 1                                   Federated states
 2                                  Republic of India
 3                     28 States 8  Union territories
 4  States: Sikkim – 610,577 (lowest) Uttar Prades...
 5  States: Goa – 3,702 km2 (1,429 sq mi) (smalles...
 6  State Governments Union Government (union terr...
 7                                Divisions Districts  ,
               This article is part of a series on the
 0                                   Politics of India
 1   Constitution Amendment Basic structure doctrin...
 2   Government President of India Droupadi Murmu (...
 3   Parliament Lok Sabha (18th) Speaker Om Birla D...
 4   Law and judiciary Law of India Indian criminal...
 5   Elections and politics Election Commission Chi...
 6   Administrative divisions States and union terr...
 7   Federalism Executive Governor List Lieutenant ...
 8   Foreign relations Ministry of External Affairs...
 9                        India portal Other countries
 10                                                vte,
                 State    ISO Vehicle code           Zone  \
 0      Andhra Pradesh  IN-AP           AP       Southern
 1   Arunachal Pradesh  IN-AR           AR  North-Eastern
 2               Assam  IN-AS           AS  North-Eastern
 3               Bihar  IN-BR           BR        Eastern
 4        Chhattisgarh  IN-CG           CG        Central
 5                 Goa  IN-GA           GA        Western
 6             Gujarat  IN-GJ           GJ        Western
 7             Haryana  IN-HR           HR       Northern
 8    Himachal Pradesh  IN-HP           HP       Northern
 9           Jharkhand  IN-JH           JH        Eastern
 10          Karnataka  IN-KA           KA       Southern
 11             Kerala  IN-KL           KL       Southern
 12     Madhya Pradesh  IN-MP           MP        Central
 13        Maharashtra  IN-MH           MH        Western
 14            Manipur  IN-MN           MN  North-Eastern
 15          Meghalaya  IN-ML           ML  North-Eastern
 16            Mizoram  IN-MZ           MZ  North-Eastern
 17           Nagaland  IN-NL           NL  North-Eastern
 18             Odisha  IN-OD           OD        Eastern
 19             Punjab  IN-PB           PB       Northern
 20          Rajasthan  IN-RJ           RJ       Northern
 21             Sikkim  IN-SK           SK  North-Eastern
 22         Tamil Nadu  IN-TN           TN       Southern
 23          Telangana  IN-TS       TG[41]       Southern
 24            Tripura  IN-TR           TR  North-Eastern
 25      Uttar Pradesh  IN-UP           UP        Central
 26        Uttarakhand  IN-UK           UK        Central
 27        West Bengal  IN-WB           WB        Eastern

                                        Capital        Largest city  \
 0                                    Amaravati       Visakhapatnam
 1                                     Itanagar            Itanagar
 2                                       Dispur            Guwahati
 3                                        Patna               Patna
 4                                    Raipur[b]           Raipur[b]
 5                                       Panaji       Vasco da Gama
 6                                  Gandhinagar           Ahmedabad
 7                                   Chandigarh           Faridabad
 8     Shimla (Summer) Dharamshala (Winter)[33]              Shimla
 9                                       Ranchi          Jamshedpur
 10                                   Bengaluru           Bengaluru
 11                          Thiruvananthapuram  Thiruvananthapuram
 12                                      Bhopal              Indore
 13     Mumbai (Summer) Nagpur (Winter)[38][39]              Mumbai
 14                                      Imphal              Imphal
 15                                    Shillong            Shillong
 16                                      Aizawl              Aizawl
 17                                      Kohima             Dimapur
 18                                 Bhubaneswar         Bhubaneswar
 19                                  Chandigarh            Ludhiana
 20                                      Jaipur              Jaipur
 21                                     Gangtok             Gangtok
 22                                     Chennai             Chennai
 23                                Hyderabad[c]        Hyderabad[c]
 24                                    Agartala            Agartala
 25                                     Lucknow             Lucknow
 26  Bhararisain (Summer) Dehradun (Winter)[47]            Dehradun
 27                                     Kolkata             Kolkata

            Statehood Population (2011)[27][28]   Area (km2)  \
 0    1 November 1956                  49506799       162975
 1   20 February 1987                   1383727        83743
 2    26 January 1950                  31205576        78438
 3    26 January 1950                 104099452        94163
 4    1 November 2000                  25545198       135194
 5        30 May 1987                   1458545         3702
 6         1 May 1960                  60439692       196024
 7    1 November 1966                  25351462        44212
 8    25 January 1971                   6864602        55673
 9   15 November 2000                  32988134        79714
 10   1 November 1956                  61095297       191791
 11   1 November 1956                  33406061        38863
 12   1 November 1956                  72626809       308252
 13        1 May 1960                 112374333       307713
 14   21 January 1972                   2855794        22327
 15   21 January 1972                   2966889        22429
 16  20 February 1987                   1097206        21081
 17   1 December 1963                   1978502        16579
 18   26 January 1950                  41974218       155707
 19   1 November 1966                  27743338        50362
 20   26 January 1950                  68548437       342239
 21       16 May 1975                    610577         7096
 22   1 November 1956                  72147030       130058
 23       2 June 2014            35,193,978[45]  112,077[45]
 24   21 January 1972                   3673917        10491
 25   26 January 1950                 199812341       240928
 26   9 November 2000                  10086292        53483
 27   26 January 1950                  91276115        88752

                     Official languages[29]  \
 0                                   Telugu
 1                                  English
 2                           Assamese, Boro
 3                                    Hindi
 4                                    Hindi
 5                                  Konkani
 6                          Gujarati, Hindi
 7                                    Hindi
 8                                    Hindi
 9                                    Hindi
 10                                 Kannada
 11                               Malayalam
 12                                   Hindi
 13                                 Marathi
 14                                  Meitei
 15                                 English
 16                           Mizo, English
 17                                 English
 18                                    Odia
 19                                 Punjabi
 20                                   Hindi
 21  Nepali, Sikkimese, Lepcha, English[40]
 22                                   Tamil
 23                                  Telugu
 24              Bengali, English, Kokborok
 25                                   Hindi
 26                                   Hindi
 27                        Bengali, English

                     Additional official languages[29]
 0                                            Urdu[30]
 1                                                   —
 2                                 Bengali, Meitei[31]
 3                                                Urdu
 4                                       Chhattisgarhi
 5                                             Marathi
 6                                                   —
 7                                         Punjabi[32]
 8                                        Sanskrit[34]
 9   Angika, Bengali, Bhojpuri, Bhumij, Ho, Kharia,...
 10                                                  —
 11                                        English[37]
 12                                                  —
 13                                                  —
 14                                            English
 15                                                  —
 16                                                  —
 17                                                  —
 18                                                  —
 19                                                  —
 20                                            English
 21  Gurung, Limbu, Magar, Mukhia, Newari, Rai, She...
 22                                            English
 23                                           Urdu[46]
 24                                                  —
 25                                               Urdu
 26                                       Sanskrit[48]
 27  Nepali,[d] Hindi, Odia, Punjabi, Santali, Telu...  ,
     Map                                 State  \
 0   NaN                           Ajmer State
 1   NaN                          Andhra State
 2   NaN                          Bhopal State
 3   NaN                        Bilaspur State
 4   NaN                          Bombay State
 5   NaN                           Coorg State
 6   NaN                           East Punjab
 7   NaN                       Hyderabad State
 8   NaN                     Jammu and Kashmir
 9   NaN                           Kutch State
 10  NaN                         Madhya Bharat
 11  NaN                          Madras State
 12  NaN                          Mysore State
 13  NaN  Patiala and East Punjab States Union
 14  NaN                            Saurashtra
 15  NaN                     Travancore–Cochin
 16  NaN                       Vindhya Pradesh

                                       Capital      Years  \
 0                                       Ajmer  1950–1956
 1                                     Kurnool  1953–1956
 2                                      Bhopal  1949–1956
 3                                    Bilaspur  1950–1954
 4                                      Bombay  1950–1960
 5                                    Madikeri  1950–1956
 6   Shimla (1947–1953) Chandigarh (1953–1966)  1947–1966
 7                                   Hyderabad  1948–1956
 8            Srinagar (Summer) Jammu (Winter)  1952–2019
 9                                        Bhuj  1947–1956
 10           Indore (Summer) Gwalior (Winter)  1948–1956
 11                                     Madras  1950–1969
 12                                  Bangalore  1947–1973
 13                                    Patiala  1948–1956
 14                                     Rajkot  1948–1956
 15                                 Trivandrum  1949–1956
 16                                       Rewa  1948–1956

                                  Present-day state(s)
 0                                           Rajasthan
 1                                      Andhra Pradesh
 2                                      Madhya Pradesh
 3                                    Himachal Pradesh
 4       Maharashtra, Gujarat, and partially Karnataka
 5                                           Karnataka
 6   Punjab, Haryana, Himachal Pradesh and Chandiga...
 7   Telangana, and partially Maharashtra and Karna...
 8                  Jammu and Kashmir UT and Ladakh UT
 9                                             Gujarat
 10                                     Madhya Pradesh
 11  Andhra Pradesh, Tamil Nadu, and partially Karn...
 12                                          Karnataka
 13                                 Punjab and Haryana
 14                                            Gujarat
 15                    Kerala and partially Tamil Nadu
 16                                     Madhya Pradesh  ,
             vteStates and union territories of India  \
 0                                             States
 1                                  Union territories
 2  Capitals in India Autonomous administrative di...

           vteStates and union territories of India.1
 0  Andhra Pradesh Arunachal Pradesh Assam Bihar C...
 1  Andaman and Nicobar Islands Chandigarh Dadra a...
 2  Capitals in India Autonomous administrative di...  ]

In [123]:
## read pickling

In [143]:
df1.to_pickle('df1_csv')

In [149]:
pd.read_pickle('C:\\Users\\Mohan\\python_workspace\\fundamental\\df1_csv')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/